package com.example.journal;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class MainActivity2 extends AppCompatActivity implements View.OnClickListener {

    EditText Homework, editText2, editText3, editText7, editText9, editText11, editText13, editText15, editText17, editText19, editText21,
            editText23, editText25, editText27, editText29, editText31, editText33, editText35, editText37, editText39, editText41, editText43,
            editText45, editText47, editText49, editText51, editText53, editText55, editText57, editText59, editText61, editText63, editText65,
            editText67, editText69, editText71, editText73, editText75, editText77, editText79, editText81, editText83, editText4, editText5,
            editText6, editText8, editText10, editText12, editText14, editText16, editText18, editText20, editText22, editText24, editText26,
            editText28, editText30, editText32, editText34, editText36, editText38, editText40, editText42, editText44, editText46, editText48,
            editText50, editText52, editText54, editText56, editText58, editText60, editText62, editText64, editText66, editText68, editText70,
            editText72, editText74, editText76, editText78, editText80, editText82, editText84;

    SharedPreferences sPref;
    final String SAVED_TEXT = "saved_text";
    final String SAVED_TEXT1 = "saved_text1";
    final String SAVED_TEXT2 = "saved_text2";
    final String SAVED_TEXT3 = "saved_text3";
    final String SAVED_TEXT4 = "saved_text4";
    final String SAVED_TEXT5 = "saved_text5";
    final String SAVED_TEXT6 = "saved_text6";
    final String SAVED_TEXT7 = "saved_text7";
    final String SAVED_TEXT8 = "saved_text8";
    final String SAVED_TEXT9 = "saved_text9";
    final String SAVED_TEXT10 = "saved_text10";
    final String SAVED_TEXT11 = "saved_text11";
    final String SAVED_TEXT12 = "saved_text12";
    final String SAVED_TEXT13 = "saved_text13";
    final String SAVED_TEXT14 = "saved_text14";
    final String SAVED_TEXT15 = "saved_text15";
    final String SAVED_TEXT16 = "saved_text16";
    final String SAVED_TEXT17 = "saved_text17";
    final String SAVED_TEXT18 = "saved_text18";
    final String SAVED_TEXT19 = "saved_text19";
    final String SAVED_TEXT20 = "saved_text20";
    final String SAVED_TEXT21 = "saved_text21";
    final String SAVED_TEXT22 = "saved_text22";
    final String SAVED_TEXT23 = "saved_text23";
    final String SAVED_TEXT24 = "saved_text24";
    final String SAVED_TEXT25 = "saved_text25";
    final String SAVED_TEXT26 = "saved_text26";
    final String SAVED_TEXT27 = "saved_text27";
    final String SAVED_TEXT28 = "saved_text28";
    final String SAVED_TEXT29 = "saved_text29";
    final String SAVED_TEXT30 = "saved_text30";
    final String SAVED_TEXT31 = "saved_text31";
    final String SAVED_TEXT32 = "saved_text32";
    final String SAVED_TEXT33 = "saved_text33";
    final String SAVED_TEXT34 = "saved_text34";
    final String SAVED_TEXT35 = "saved_text35";
    final String SAVED_TEXT36 = "saved_text36";
    final String SAVED_TEXT37 = "saved_text37";
    final String SAVED_TEXT38 = "saved_text38";
    final String SAVED_TEXT39 = "saved_text39";
    final String SAVED_TEXT40 = "saved_text40";
    final String SAVED_TEXT41 = "saved_text41";
    final String SAVED_TEXT42 = "saved_text42";
    final String SAVED_TEXT43 = "saved_text43";
    final String SAVED_TEXT44 = "saved_text44";
    final String SAVED_TEXT45 = "saved_text45";
    final String SAVED_TEXT46 = "saved_text46";
    final String SAVED_TEXT47 = "saved_text47";
    final String SAVED_TEXT48 = "saved_text48";
    final String SAVED_TEXT49 = "saved_text49";
    final String SAVED_TEXT50 = "saved_text50";
    final String SAVED_TEXT51 = "saved_text51";
    final String SAVED_TEXT52 = "saved_text52";
    final String SAVED_TEXT53 = "saved_text53";
    final String SAVED_TEXT54 = "saved_text54";
    final String SAVED_TEXT55 = "saved_text55";
    final String SAVED_TEXT56 = "saved_text56";
    final String SAVED_TEXT57 = "saved_text57";
    final String SAVED_TEXT58 = "saved_text58";
    final String SAVED_TEXT59 = "saved_text59";
    final String SAVED_TEXT60 = "saved_text60";
    final String SAVED_TEXT61 = "saved_text61";
    final String SAVED_TEXT62 = "saved_text62";
    final String SAVED_TEXT63 = "saved_text63";
    final String SAVED_TEXT64 = "saved_text64";
    final String SAVED_TEXT65 = "saved_text65";
    final String SAVED_TEXT66 = "saved_text66";
    final String SAVED_TEXT67 = "saved_text67";
    final String SAVED_TEXT68 = "saved_text68";
    final String SAVED_TEXT69 = "saved_text69";
    final String SAVED_TEXT70 = "saved_text70";
    final String SAVED_TEXT71 = "saved_text71";
    final String SAVED_TEXT72 = "saved_text72";
    final String SAVED_TEXT73 = "saved_text73";
    final String SAVED_TEXT74 = "saved_text74";
    final String SAVED_TEXT75 = "saved_text75";
    final String SAVED_TEXT76 = "saved_text76";
    final String SAVED_TEXT77 = "saved_text77";
    final String SAVED_TEXT78 = "saved_text78";
    final String SAVED_TEXT79 = "saved_text79";
    final String SAVED_TEXT80 = "saved_text80";
    final String SAVED_TEXT81 = "saved_text81";
    final String SAVED_TEXT82 = "saved_text82";
    final String SAVED_TEXT83 = "saved_text83";
    final String SAVED_TEXT84 = "saved_text84";
    final String SAVED_TEXT85 = "saved_text85";
    Button Butt1;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        Homework = (EditText) findViewById(R.id.Homework);
        editText2 = (EditText) findViewById(R.id.editText2);
        editText3 = (EditText) findViewById(R.id.editText3);
        editText4 = (EditText) findViewById(R.id.editText4);
        editText5 = (EditText) findViewById(R.id.editText5);
        editText6 = (EditText) findViewById(R.id.editText6);
        editText7 = (EditText) findViewById(R.id.editText7);
        editText8 = (EditText) findViewById(R.id.editText8);
        editText9 = (EditText) findViewById(R.id.editText9);
        editText10 = (EditText) findViewById(R.id.editText10);
        editText11 = (EditText) findViewById(R.id.editText11);
        editText12 = (EditText) findViewById(R.id.editText12);
        editText13 = (EditText) findViewById(R.id.editText13);
        editText14 = (EditText) findViewById(R.id.editText14);
        editText15 = (EditText) findViewById(R.id.editText15);
        editText16 = (EditText) findViewById(R.id.editText16);
        editText17 = (EditText) findViewById(R.id.editText17);
        editText18 = (EditText) findViewById(R.id.editText18);
        editText19 = (EditText) findViewById(R.id.editText19);
        editText20 = (EditText) findViewById(R.id.editText20);
        editText21 = (EditText) findViewById(R.id.editText21);
        editText22 = (EditText) findViewById(R.id.editText22);
        editText23 = (EditText) findViewById(R.id.editText23);
        editText24 = (EditText) findViewById(R.id.editText24);
        editText25 = (EditText) findViewById(R.id.editText25);
        editText26 = (EditText) findViewById(R.id.editText26);
        editText27 = (EditText) findViewById(R.id.editText27);
        editText28 = (EditText) findViewById(R.id.editText28);
        editText29 = (EditText) findViewById(R.id.editText29);
        editText30 = (EditText) findViewById(R.id.editText30);
        editText31 = (EditText) findViewById(R.id.editText31);
        editText32 = (EditText) findViewById(R.id.editText32);
        editText33 = (EditText) findViewById(R.id.editText33);
        editText34 = (EditText) findViewById(R.id.editText34);
        editText35 = (EditText) findViewById(R.id.editText35);
        editText37 = (EditText) findViewById(R.id.editText36);
        editText36 = (EditText) findViewById(R.id.editText37);
        editText38 = (EditText) findViewById(R.id.editText38);
        editText39 = (EditText) findViewById(R.id.editText39);
        editText40 = (EditText) findViewById(R.id.editText40);
        editText41 = (EditText) findViewById(R.id.editText41);
        editText42 = (EditText) findViewById(R.id.editText42);
        editText43 = (EditText) findViewById(R.id.editText43);
        editText44 = (EditText) findViewById(R.id.editText44);
        editText45 = (EditText) findViewById(R.id.editText45);
        editText46 = (EditText) findViewById(R.id.editText46);
        editText47 = (EditText) findViewById(R.id.editText47);
        editText48 = (EditText) findViewById(R.id.editText48);
        editText49 = (EditText) findViewById(R.id.editText49);
        editText50 = (EditText) findViewById(R.id.editText50);
        editText51 = (EditText) findViewById(R.id.editText51);
        editText52 = (EditText) findViewById(R.id.editText52);
        editText53 = (EditText) findViewById(R.id.editText53);
        editText54 = (EditText) findViewById(R.id.editText54);
        editText55 = (EditText) findViewById(R.id.editText55);
        editText56 = (EditText) findViewById(R.id.editText56);
        editText57 = (EditText) findViewById(R.id.editText57);
        editText58 = (EditText) findViewById(R.id.editText58);
        editText59 = (EditText) findViewById(R.id.editText59);
        editText60 = (EditText) findViewById(R.id.editText60);
        editText61 = (EditText) findViewById(R.id.editText61);
        editText62 = (EditText) findViewById(R.id.editText62);
        editText63 = (EditText) findViewById(R.id.editText63);
        editText64 = (EditText) findViewById(R.id.editText64);
        editText65 = (EditText) findViewById(R.id.editText65);
        editText66 = (EditText) findViewById(R.id.editText66);
        editText67 = (EditText) findViewById(R.id.editText67);
        editText68 = (EditText) findViewById(R.id.editText68);
        editText69 = (EditText) findViewById(R.id.editText69);
        editText70 = (EditText) findViewById(R.id.editText70);
        editText71 = (EditText) findViewById(R.id.editText71);
        editText72 = (EditText) findViewById(R.id.editText72);
        editText73 = (EditText) findViewById(R.id.editText73);
        editText74 = (EditText) findViewById(R.id.editText74);
        editText75 = (EditText) findViewById(R.id.editText75);
        editText76 = (EditText) findViewById(R.id.editText76);
        editText77 = (EditText) findViewById(R.id.editText77);
        editText78 = (EditText) findViewById(R.id.editText78);
        editText79 = (EditText) findViewById(R.id.editText79);
        editText80 = (EditText) findViewById(R.id.editText80);
        editText81 = (EditText) findViewById(R.id.editText81);
        editText82 = (EditText) findViewById(R.id.editText82);
        editText83 = (EditText) findViewById(R.id.editText83);
        editText84 = (EditText) findViewById(R.id.editText84);

        Butt1 = (Button) findViewById(R.id.Butt);
        Butt1.setOnClickListener(this);
        loadText();
    }

            @Override
            public void onClick(View v) {
                if (v.getId() == R.id.Butt) {
                    saveText();
                }
            }



    private void saveText() {
        sPref = getPreferences(MODE_PRIVATE);
        SharedPreferences.Editor ed = sPref.edit();
        ed.putString(SAVED_TEXT, Homework.getText().toString());
        ed.putString(SAVED_TEXT1, editText2.getText().toString());
        ed.putString(SAVED_TEXT2, editText3.getText().toString());
        ed.putString(SAVED_TEXT3, editText4.getText().toString());
        ed.putString(SAVED_TEXT4, editText5.getText().toString());
        ed.putString(SAVED_TEXT5, editText6.getText().toString());
        ed.putString(SAVED_TEXT6, editText7.getText().toString());
        ed.putString(SAVED_TEXT7, editText8.getText().toString());
        ed.putString(SAVED_TEXT8, editText9.getText().toString());
        ed.putString(SAVED_TEXT9, editText10.getText().toString());
        ed.putString(SAVED_TEXT10, editText11.getText().toString());
        ed.putString(SAVED_TEXT11, editText12.getText().toString());
        ed.putString(SAVED_TEXT12, editText13.getText().toString());
        ed.putString(SAVED_TEXT13, editText14.getText().toString());
        ed.putString(SAVED_TEXT14, editText15.getText().toString());
        ed.putString(SAVED_TEXT15, editText16.getText().toString());
        ed.putString(SAVED_TEXT16, editText17.getText().toString());
        ed.putString(SAVED_TEXT17, editText18.getText().toString());
        ed.putString(SAVED_TEXT18, editText19.getText().toString());
        ed.putString(SAVED_TEXT19, editText20.getText().toString());
        ed.putString(SAVED_TEXT20, editText21.getText().toString());
        ed.putString(SAVED_TEXT21, editText22.getText().toString());
        ed.putString(SAVED_TEXT22, editText23.getText().toString());
        ed.putString(SAVED_TEXT23, editText24.getText().toString());
        ed.putString(SAVED_TEXT24, editText25.getText().toString());
        ed.putString(SAVED_TEXT25, editText26.getText().toString());
        ed.putString(SAVED_TEXT26, editText27.getText().toString());
        ed.putString(SAVED_TEXT27, editText28.getText().toString());
        ed.putString(SAVED_TEXT28, editText29.getText().toString());
        ed.putString(SAVED_TEXT29, editText30.getText().toString());
        ed.putString(SAVED_TEXT30, editText31.getText().toString());
        ed.putString(SAVED_TEXT31, editText32.getText().toString());
        ed.putString(SAVED_TEXT32, editText33.getText().toString());
        ed.putString(SAVED_TEXT33, editText34.getText().toString());
        ed.putString(SAVED_TEXT34, editText35.getText().toString());
        ed.putString(SAVED_TEXT35, editText36.getText().toString());
        ed.putString(SAVED_TEXT36, editText37.getText().toString());
        ed.putString(SAVED_TEXT37, editText38.getText().toString());
        ed.putString(SAVED_TEXT38, editText39.getText().toString());
        ed.putString(SAVED_TEXT39, editText40.getText().toString());
        ed.putString(SAVED_TEXT40, editText41.getText().toString());
        ed.putString(SAVED_TEXT41, editText42.getText().toString());
        ed.putString(SAVED_TEXT42, editText43.getText().toString());
        ed.putString(SAVED_TEXT43, editText44.getText().toString());
        ed.putString(SAVED_TEXT44, editText45.getText().toString());
        ed.putString(SAVED_TEXT45, editText46.getText().toString());
        ed.putString(SAVED_TEXT46, editText47.getText().toString());
        ed.putString(SAVED_TEXT47, editText48.getText().toString());
        ed.putString(SAVED_TEXT48, editText49.getText().toString());
        ed.putString(SAVED_TEXT49, editText50.getText().toString());
        ed.putString(SAVED_TEXT50, editText51.getText().toString());
        ed.putString(SAVED_TEXT51, editText52.getText().toString());
        ed.putString(SAVED_TEXT52, editText53.getText().toString());
        ed.putString(SAVED_TEXT53, editText54.getText().toString());
        ed.putString(SAVED_TEXT54, editText55.getText().toString());
        ed.putString(SAVED_TEXT55, editText56.getText().toString());
        ed.putString(SAVED_TEXT56, editText57.getText().toString());
        ed.putString(SAVED_TEXT57, editText58.getText().toString());
        ed.putString(SAVED_TEXT58, editText59.getText().toString());
        ed.putString(SAVED_TEXT59, editText60.getText().toString());
        ed.putString(SAVED_TEXT60, editText61.getText().toString());
        ed.putString(SAVED_TEXT61, editText62.getText().toString());
        ed.putString(SAVED_TEXT62, editText63.getText().toString());
        ed.putString(SAVED_TEXT63, editText64.getText().toString());
        ed.putString(SAVED_TEXT64, editText65.getText().toString());
        ed.putString(SAVED_TEXT65, editText66.getText().toString());
        ed.putString(SAVED_TEXT66, editText67.getText().toString());
        ed.putString(SAVED_TEXT67, editText68.getText().toString());
        ed.putString(SAVED_TEXT68, editText69.getText().toString());
        ed.putString(SAVED_TEXT69, editText70.getText().toString());
        ed.putString(SAVED_TEXT70, editText71.getText().toString());
        ed.putString(SAVED_TEXT71, editText72.getText().toString());
        ed.putString(SAVED_TEXT72, editText73.getText().toString());
        ed.putString(SAVED_TEXT73, editText74.getText().toString());
        ed.putString(SAVED_TEXT74, editText75.getText().toString());
        ed.putString(SAVED_TEXT75, editText76.getText().toString());
        ed.putString(SAVED_TEXT76, editText77.getText().toString());
        ed.putString(SAVED_TEXT77, editText78.getText().toString());
        ed.putString(SAVED_TEXT78, editText79.getText().toString());
        ed.putString(SAVED_TEXT79, editText80.getText().toString());
        ed.putString(SAVED_TEXT80, editText81.getText().toString());
        ed.putString(SAVED_TEXT81, editText82.getText().toString());
        ed.putString(SAVED_TEXT82, editText83.getText().toString());
        ed.putString(SAVED_TEXT83, editText84.getText().toString());


        ed.commit();
        Toast.makeText(MainActivity2.this, "Сохранено", Toast.LENGTH_SHORT).show();

    }


    private void loadText(){
        sPref = getPreferences(MODE_PRIVATE);
        String savedText = sPref.getString(SAVED_TEXT, "");
        String savedText1 = sPref.getString(SAVED_TEXT1, "");
        String savedText2 = sPref.getString(SAVED_TEXT2, "");
        String savedText3 = sPref.getString(SAVED_TEXT3, "");
        String savedText4 = sPref.getString(SAVED_TEXT4, "");
        String savedText5 = sPref.getString(SAVED_TEXT5, "");
        String savedText6 = sPref.getString(SAVED_TEXT6, "");
        String savedText7 = sPref.getString(SAVED_TEXT7, "");
        String savedText8 = sPref.getString(SAVED_TEXT8, "");
        String savedText9 = sPref.getString(SAVED_TEXT9, "");
        String savedText10 = sPref.getString(SAVED_TEXT10, "");
        String savedText11 = sPref.getString(SAVED_TEXT11, "");
        String savedText12 = sPref.getString(SAVED_TEXT12, "");
        String savedText13 = sPref.getString(SAVED_TEXT13, "");
        String savedText14 = sPref.getString(SAVED_TEXT14, "");
        String savedText15 = sPref.getString(SAVED_TEXT15, "");
        String savedText16 = sPref.getString(SAVED_TEXT16, "");
        String savedText17 = sPref.getString(SAVED_TEXT17, "");
        String savedText18 = sPref.getString(SAVED_TEXT18, "");
        String savedText19 = sPref.getString(SAVED_TEXT19, "");
        String savedText20 = sPref.getString(SAVED_TEXT20, "");
        String savedText21 = sPref.getString(SAVED_TEXT21, "");
        String savedText22 = sPref.getString(SAVED_TEXT22, "");
        String savedText23 = sPref.getString(SAVED_TEXT23, "");
        String savedText24 = sPref.getString(SAVED_TEXT24, "");
        String savedText25 = sPref.getString(SAVED_TEXT25, "");
        String savedText26 = sPref.getString(SAVED_TEXT26, "");
        String savedText27 = sPref.getString(SAVED_TEXT27, "");
        String savedText28 = sPref.getString(SAVED_TEXT28, "");
        String savedText29 = sPref.getString(SAVED_TEXT29, "");
        String savedText30 = sPref.getString(SAVED_TEXT30, "");
        String savedText31 = sPref.getString(SAVED_TEXT31, "");
        String savedText32 = sPref.getString(SAVED_TEXT32, "");
        String savedText33 = sPref.getString(SAVED_TEXT33, "");
        String savedText34 = sPref.getString(SAVED_TEXT34, "");
        String savedText35 = sPref.getString(SAVED_TEXT35, "");
        String savedText36 = sPref.getString(SAVED_TEXT36, "");
        String savedText37 = sPref.getString(SAVED_TEXT37, "");
        String savedText38 = sPref.getString(SAVED_TEXT38, "");
        String savedText39 = sPref.getString(SAVED_TEXT39, "");
        String savedText40 = sPref.getString(SAVED_TEXT40, "");
        String savedText41 = sPref.getString(SAVED_TEXT41, "");
        String savedText42 = sPref.getString(SAVED_TEXT42, "");
        String savedText43 = sPref.getString(SAVED_TEXT43, "");
        String savedText44 = sPref.getString(SAVED_TEXT44, "");
        String savedText45 = sPref.getString(SAVED_TEXT45, "");
        String savedText46 = sPref.getString(SAVED_TEXT46, "");
        String savedText47 = sPref.getString(SAVED_TEXT47, "");
        String savedText48 = sPref.getString(SAVED_TEXT48, "");
        String savedText49 = sPref.getString(SAVED_TEXT49, "");
        String savedText50 = sPref.getString(SAVED_TEXT50, "");
        String savedText51 = sPref.getString(SAVED_TEXT51, "");
        String savedText52 = sPref.getString(SAVED_TEXT52, "");
        String savedText53= sPref.getString(SAVED_TEXT53, "");
        String savedText54 = sPref.getString(SAVED_TEXT54, "");
        String savedText55 = sPref.getString(SAVED_TEXT55, "");
        String savedText56 = sPref.getString(SAVED_TEXT56, "");
        String savedText57 = sPref.getString(SAVED_TEXT57, "");
        String savedText58 = sPref.getString(SAVED_TEXT58, "");
        String savedText59 = sPref.getString(SAVED_TEXT59, "");
        String savedText60 = sPref.getString(SAVED_TEXT60, "");
        String savedText61 = sPref.getString(SAVED_TEXT61, "");
        String savedText62 = sPref.getString(SAVED_TEXT62, "");
        String savedText63 = sPref.getString(SAVED_TEXT63, "");
        String savedText64 = sPref.getString(SAVED_TEXT64, "");
        String savedText65 = sPref.getString(SAVED_TEXT65, "");
        String savedText66 = sPref.getString(SAVED_TEXT66, "");
        String savedText67 = sPref.getString(SAVED_TEXT67, "");
        String savedText68 = sPref.getString(SAVED_TEXT68, "");
        String savedText69 = sPref.getString(SAVED_TEXT69, "");
        String savedText70 = sPref.getString(SAVED_TEXT70, "");
        String savedText71 = sPref.getString(SAVED_TEXT71, "");
        String savedText72 = sPref.getString(SAVED_TEXT72, "");
        String savedText73 = sPref.getString(SAVED_TEXT73, "");
        String savedText74 = sPref.getString(SAVED_TEXT74, "");
        String savedText75 = sPref.getString(SAVED_TEXT75, "");
        String savedText76 = sPref.getString(SAVED_TEXT76, "");
        String savedText77 = sPref.getString(SAVED_TEXT77, "");
        String savedText78= sPref.getString(SAVED_TEXT78, "");
        String savedText79 = sPref.getString(SAVED_TEXT79, "");
        String savedText80 = sPref.getString(SAVED_TEXT80, "");
        String savedText81 = sPref.getString(SAVED_TEXT81, "");
        String savedText82 = sPref.getString(SAVED_TEXT82, "");
        String savedText83 = sPref.getString(SAVED_TEXT83, "");
        String savedText84 = sPref.getString(SAVED_TEXT84, "");
        String savedText85 = sPref.getString(SAVED_TEXT85, "");


        Homework.setText(savedText);
        editText2.setText(savedText1);
        editText3.setText(savedText2);
        editText4.setText(savedText3);
        editText5.setText(savedText4);
        editText6.setText(savedText5);
        editText7.setText(savedText6);
        editText8.setText(savedText7);
        editText9.setText(savedText8);
        editText10.setText(savedText9);
        editText11.setText(savedText10);
        editText12.setText(savedText11);
        editText13.setText(savedText12);
        editText14.setText(savedText13);
        editText15.setText(savedText14);
        editText16.setText(savedText15);
        editText17.setText(savedText16);
        editText18.setText(savedText17);
        editText19.setText(savedText18);
        editText20.setText(savedText19);
        editText21.setText(savedText20);
        editText22.setText(savedText21);
        editText23.setText(savedText22);
        editText24.setText(savedText23);
        editText25.setText(savedText24);
        editText26.setText(savedText25);
        editText27.setText(savedText26);
        editText28.setText(savedText27);
        editText29.setText(savedText28);
        editText30.setText(savedText29);
        editText31.setText(savedText30);
        editText32.setText(savedText31);
        editText33.setText(savedText32);
        editText34.setText(savedText33);
        editText35.setText(savedText34);
        editText36.setText(savedText35);
        editText37.setText(savedText36);
        editText38.setText(savedText37);
        editText39.setText(savedText38);
        editText40.setText(savedText39);
        editText41.setText(savedText40);
        editText42.setText(savedText41);
        editText43.setText(savedText42);
        editText44.setText(savedText43);
        editText45.setText(savedText44);
        editText46.setText(savedText45);
        editText47.setText(savedText46);
        editText48.setText(savedText47);
        editText49.setText(savedText48);
        editText50.setText(savedText49);
        editText51.setText(savedText50);
        editText52.setText(savedText51);
        editText53.setText(savedText52);
        editText54.setText(savedText53);
        editText55.setText(savedText54);
        editText56.setText(savedText55);
        editText57.setText(savedText56);
        editText58.setText(savedText57);
        editText59.setText(savedText58);
        editText60.setText(savedText59);
        editText61.setText(savedText60);
        editText62.setText(savedText61);
        editText63.setText(savedText62);
        editText64.setText(savedText63);
        editText65.setText(savedText64);
        editText66.setText(savedText65);
        editText67.setText(savedText66);
        editText68.setText(savedText67);
        editText69.setText(savedText68);
        editText70.setText(savedText69);
        editText71.setText(savedText70);
        editText72.setText(savedText71);
        editText73.setText(savedText72);
        editText74.setText(savedText73);
        editText75.setText(savedText74);
        editText76.setText(savedText75);
        editText77.setText(savedText76);
        editText78.setText(savedText77);
        editText79.setText(savedText78);
        editText80.setText(savedText79);
        editText81.setText(savedText80);
        editText82.setText(savedText81);
        editText83.setText(savedText82);
        editText84.setText(savedText83);



        Toast.makeText(MainActivity2.this, "Данные загружены", Toast.LENGTH_SHORT).show();
    }
}
